### ISSUE TITLE
Wrong information about expected bias weight

### ISSUE THREAD

**Issue by Tjev** [alewarne/Layerwise-Relevance-Propagation-for-LSTMs#10]
Hello :) first of all, thank you for all the effort in rewriting from NumPy.

I tried to follow the _How can I make my model ready for use?_ instructions, but I noticed that the bias weight dimensions given in the instructions seems off. I checked both, [this repo's implementation](https://github.com/alewarne/Layerwise-Relevance-Propagation-for-LSTMs/blob/master/lstm_network.py#L54) and the original [implementation made by Arras et al.](https://github.com/ArrasL/LRP_for_LSTM/blob/master/code/LSTM/LSTM_bidi.py#L36-L39) and seems like it should be _4\*n_hidden_.

I took the liberty to create a [PR](https://github.com/alewarne/Layerwise-Relevance-Propagation-for-LSTMs/pull/9) with relevant change if it looks good to you.

Thanks!

**Comment by alewarne** [comment]
You are right, thank you.
