### ISSUE TITLE
Tuning eps and bias_factor

### ISSUE THREAD

**Issue by georgia-reb** [alewarne/Layerwise-Relevance-Propagation-for-LSTMs#11]
Is there a specific reference for explaining the choice of eps and bias_factor when computing the explanation, or could you add this information to the documentation/example code?

**Comment by alewarne** [comment]
I guess the best reference for eps and bias_factor is in the [original LRP paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0130140) and the one on [LRP for LSTMs](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0181142). From my experience, the difference in the explanations obtained is rather small when changing the both parameters.
