### ISSUE TITLE
Regression

### ISSUE THREAD

**Issue by gaImdea** [alewarne/Layerwise-Relevance-Propagation-for-LSTMs#3]
Is it possible to adapt this code in order to deal with  a regression problem? Let's say that each word of a sentence is a number and the number of words actually represents the history feed to the LSTM.

**Comment by alewarne** [comment]
I'm not sure what you mean by regression here. The setup you describe sounds like the basic LSTM setting to me.

**Comment by gaImdea** [comment]
What I mean is if it possible to use this code for a regression task rather than a classification one.

**Comment by alewarne** [comment]
Ah, I see no problem in using it for regression. If you final (dense) layer is composed of 1 unit which you interpret as the target value you can use LRP straight on. If you have d-units in the final layer each representing a single variable you want to predict then you can only explain each dimension on its own (which is still be useful I suppose).
