### ISSUE TITLE
Using LRP for clickstream data

### ISSUE THREAD

**Issue by oldbighorn** [alewarne/Layerwise-Relevance-Propagation-for-LSTMs#4]
I've trained a bidirectional LSTM model on clickstream data sequences, and I want to explain the predictions using LRP. Would it be possible to adjust this implementation, so it can be used on sequential data?
A sequence, for example, looks like: [5,4,3,4,4,3,3,4,5]

**Comment by alewarne** [comment]
This setting is pretty equal to the NLP setting from the repository. I see no problem in using it.
