### ISSUE TITLE
AssertionError when using LRP with trained LSTM

### ISSUE THREAD

**Issue by oldbighorn** [alewarne/Layerwise-Relevance-Propagation-for-LSTMs#5]
When using the example file, I'm getting an AssertionError at the step where the lrp_model is created.
My trained LSTM has two laters: a bidirectional layer with a dense layer.

This is the error message:
`---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-27-5084b5d7101c> in <module>()
      1 # our keras model has no bias in the final dense layer. Therefore we add a bias of zero to the weights
      2 weights.append(np.zeros((n_classes,)))
----> 3 lrp_model = LSTM_network(n_hidden, embedding_dim, n_classes, weights=weights)

1 frames
/content/gdrive/MyDrive/Github/Layerwise-Relevance-Propagation-for-LSTMs/lstm_network.py in check_weights(self, weights)
     49 
     50     def check_weights(self, weights):
---> 51         assert len(weights) == 8
     52         assert weights[0].shape == weights[3].shape == (self.embedding_dim, 4 * self.n_hidden)
     53         assert weights[1].shape == weights[4].shape == (self.n_hidden, 4 * self.n_hidden)`

Model information:

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 bidirectional (Bidirectiona  (None, 1, 80)            29120     
 l)                                                              
                                                                 
 dense (Dense)               (None, 1, 2)              162       
                                                                 
=================================================================
Total params: 29,282
Trainable params: 29,282
Non-trainable params: 0
_________________________________________________________________

Model weights:
`[array([[-0.14589094, -0.109157  , -0.14862502, ...,  0.05902363,
          0.12337458, -0.16252166],
        [-0.02857172,  0.05831584, -0.05961279, ...,  0.16830683,
         -0.0506602 , -0.00071155],
        [ 0.0480095 , -0.11844338,  0.03134364, ...,  0.10429633,
         -0.00907244, -0.0632805 ],
        ...,
        [ 0.03383616,  0.05454336,  0.11343476, ..., -0.0426726 ,
         -0.16350904, -0.06779504],
        [-0.16050138,  0.11912465,  0.1114012 , ...,  0.05771643,
         -0.08703788,  0.13455832],
        [ 0.03648573, -0.05416211,  0.06100845, ...,  0.1616402 ,
          0.16605195, -0.00643867]], dtype=float32),
 array([[ 0.12105513, -0.13484101, -0.08050255, ...,  0.02417273,
         -0.10804835, -0.0003512 ],
        [ 0.05524178, -0.06060602,  0.02559383, ...,  0.05737585,
          0.04954191,  0.10207085],
        [-0.0451355 , -0.08752962, -0.07947148, ...,  0.00326438,
         -0.04098763, -0.04255746],
        ...,
        [ 0.00091907,  0.01915237,  0.24856232, ..., -0.075836  ,
          0.02835973,  0.07326791],
        [ 0.04647025, -0.02618196,  0.04257794, ..., -0.0109081 ,
          0.16313094,  0.09327545],
        [ 0.04213158,  0.10886426,  0.02217796, ...,  0.07988814,
         -0.04982121, -0.07630482]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[ 0.12592539,  0.04663648, -0.14126179, ...,  0.0080165 ,
         -0.13614854,  0.13439679],
        [ 0.14059076, -0.15616359, -0.03107311, ..., -0.12985879,
          0.06290506,  0.05581011],
        [ 0.13915601,  0.10722151, -0.04732033, ...,  0.10782951,
         -0.10983871,  0.11717716],
        ...,
        [-0.10123186, -0.09026092,  0.03930029, ...,  0.13930827,
          0.02392484, -0.09822193],
        [ 0.04557046,  0.01697335, -0.15786715, ..., -0.05159738,
          0.02581862, -0.07735623],
        [ 0.06512657, -0.06831458,  0.1264781 , ..., -0.11315078,
          0.0661497 , -0.09316676]], dtype=float32),
 array([[-0.01746452, -0.05097441, -0.15952031, ..., -0.01365258,
          0.06825273, -0.06441116],
        [ 0.02869932,  0.07477645,  0.03344204, ...,  0.1252457 ,
         -0.0996536 ,  0.04137665],
        [-0.00595529,  0.05252875,  0.04065241, ...,  0.02345328,
          0.02543715, -0.02803543],
        ...,
        [-0.08704507,  0.02779714,  0.10145421, ...,  0.05849427,
         -0.01602693,  0.1045105 ],
        [ 0.05657658,  0.06907408,  0.06015037, ..., -0.06372479,
         -0.02493863, -0.08307693],
        [-0.03829911, -0.04722971,  0.01023382, ...,  0.01119014,
          0.10807898,  0.03149179]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[ 0.2464819 ,  0.09616047],
        [-0.06194112, -0.0181596 ],
        [ 0.12193146, -0.11114621],
        [-0.06511505, -0.10939299],
        [-0.15291828, -0.0568773 ],
        [ 0.06723434,  0.03025889],
        [ 0.14863017,  0.08541191],
        [ 0.1816768 , -0.01948264],
        [-0.18243092, -0.01101705],
        [-0.08724479,  0.21128356],
        [ 0.21356529, -0.03654651],
        [ 0.05121288,  0.26642418],
        [ 0.21226275, -0.13820459],
        [-0.08905445,  0.23865074],
        [-0.17191531,  0.16079849],
        [-0.23709749, -0.13307853],
        [-0.21238127,  0.18488184],
        [-0.1341851 ,  0.25618273],
        [ 0.01142639,  0.2213512 ],
        [-0.03322521, -0.04274631],
        [-0.16619489,  0.1602149 ],
        [ 0.24289536, -0.23904704],
        [ 0.08527952,  0.13992125],
        [ 0.0150539 , -0.25602737],
        [-0.03351833,  0.22729748],
        [ 0.0049932 , -0.12270647],
        [ 0.07471764,  0.23825741],
        [ 0.02821124,  0.21491885],
        [-0.09753837, -0.21534497],
        [-0.21110207,  0.02326971],
        [-0.0846099 , -0.18572403],
        [-0.17176045, -0.01635289],
        [-0.03010617, -0.00566217],
        [ 0.13852504, -0.05127522],
        [-0.07036428, -0.1653957 ],
        [ 0.09539115,  0.068441  ],
        [-0.13147049,  0.00648311],
        [-0.15396976, -0.15899062],
        [ 0.15774193, -0.15042713],
        [-0.2025465 , -0.08748437],
        [-0.2351891 ,  0.11362112],
        [-0.18344888, -0.02351131],
        [-0.24854109,  0.10026711],
        [ 0.2543264 , -0.02693398],
        [ 0.12296826,  0.14596698],
        [-0.12206601, -0.19836242],
        [-0.22912745,  0.02835953],
        [ 0.22066745, -0.02335955],
        [-0.06980494, -0.16293925],
        [-0.06051339,  0.1406219 ],
        [-0.12420128, -0.04553637],
        [ 0.10753682, -0.1802605 ],
        [-0.02201682,  0.16343132],
        [ 0.17316446,  0.11112338],
        [ 0.21630022,  0.15870467],
        [-0.15919572,  0.22165883],
        [ 0.26980805,  0.14199957],
        [-0.26815718, -0.08748437],
        [-0.1494602 , -0.03418048],
        [ 0.22346166, -0.08121282],
        [-0.12099543, -0.20847471],
        [-0.20938334, -0.15634838],
        [-0.01379299, -0.26488155],
        [ 0.04208732, -0.15692732],
        [-0.00552228,  0.18390521],
        [ 0.04481599,  0.15910125],
        [ 0.26345623, -0.18703324],
        [ 0.17066926, -0.21129715],
        [ 0.10102999,  0.08798704],
        [ 0.22355866, -0.04269277],
        [-0.07668757, -0.075455  ],
        [-0.23726453,  0.11776036],
        [-0.01933742, -0.19082855],
        [ 0.06154385,  0.1935738 ],
        [ 0.02714002, -0.06824829],
        [ 0.20803222, -0.04703814],
        [ 0.1945132 , -0.1507062 ],
        [-0.16616   ,  0.09627032],
        [-0.16609474, -0.1767674 ],
        [-0.26527643, -0.02303638]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([0., 0.])]`

Is someone able to tell me what's going wrong here?

**Comment by alewarne** [comment]
Apparently your weight list has not eight entries (after adding the zero bias). I cannot say why because the example notebook is still running fine on my machine - tested with tensorflow 2.5.
