### ISSUE TITLE
Which LRP gating rule is being used?

### ISSUE THREAD

**Issue by memphisbarbecue** [alewarne/Layerwise-Relevance-Propagation-for-LSTMs#7]
I assume that the code here is an adaptation of Arras et al.'s numpy code but I have been looking for some answers related to what specifically was implemented. I apologize if the answer to this is in the paper or the code somewhere that I've missed.

In Arras et al.'s paper from 2019, they mention the LRP-all, LRP-prop, LRP-abs, and LRP-half rules. Is LRP-all what's being used here? I read it as LRP-all and the paper said that LRP-all was the most competitive rule but would appreciate any further explanation here.

**Comment by alewarne** [comment]
It's been some time since I implemented this but I'm pretty sure that the LRP-all rule is used here indeed.
