### ISSUE TITLE
dimension check too restrictive for uni directional LSTM

### ISSUE THREAD

**Issue by nicrie** [alewarne/Layerwise-Relevance-Propagation-for-LSTMs#8]
this is a really minor thing but just in case: it seems that checking the dimensions of the linear layer in
https://github.com/alewarne/Layerwise-Relevance-Propagation-for-LSTMs/blob/b68f2799269440c11228900bfab2364871ff816b/lstm_network.py#L55

is correct for bidirectional LSTMs but I would expect `self.n_hidden` instead of `2 * self.n_hidden` for unidirectional ones.

**Comment by alewarne** [comment]
Yes that's right. Don't hesitate to make a pull request on this ;-)
